// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADAWyqx2iwiRQWYhikHZHqngE1xqUQ3fg',
    appId: '1:265535017648:web:d4f76485365a5be7946175',
    messagingSenderId: '265535017648',
    projectId: 'toko-telur-erp',
    authDomain: 'toko-telur-erp.firebaseapp.com',
    databaseURL: 'https://toko-telur-erp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'toko-telur-erp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlu0IMnlovvKCZ3MlGxFZs4bBp5NQLvok',
    appId: '1:265535017648:android:90655b9f76f65937946175',
    messagingSenderId: '265535017648',
    projectId: 'toko-telur-erp',
    databaseURL: 'https://toko-telur-erp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'toko-telur-erp.firebasestorage.app',
  );

}